# Generated by Django 5.1.5 on 2025-07-07 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles_creation', '0001_initial'),
    ]

    operations = [
    ]


from django.db import migrations


def create_new_permissions(apps, schema_editor):
    Permission = apps.get_model('roles_creation', 'Permission')

    permissions = [
        "create_users", "update_users", "delete_users", "view_users",
        "create_organization", "update_organization", "delete_organization", "view_organization",
        "create_category", "update_category", "delete_category", "view_category",
        "create_roles", "update_roles", "delete_roles", "view_roles",
        "create_visitor", "update_visitor", "delete_visitor", "view_visitor",
        "create_personal_details","update_personal_details","delete_personal_details","view_personal_details",
        "create_report", "update_report", "delete_report", "view_report",
        
    ]
    




    for perm in permissions:
        Permission.objects.get_or_create(name=perm)


class Migration(migrations.Migration):

    dependencies = [
        ('roles_creation', '0001_initial'),  # Make sure the dependency is correct
    ]

    operations = [
        migrations.RunPython(create_new_permissions),
]

