# Generated by Django 5.1.5 on 2025-11-19 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles_creation', '0002_add_new_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='permission',
            field=models.ManyToManyField(related_name='role_permissions', to='roles_creation.permission'),
        ),
    ]
