# Generated by Django 5.1.5 on 2025-11-27 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles_creation', '0003_alter_rolepermission_modified_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='roles_creation.role'),
        ),
    ]
