# Generated by Django 5.1.5 on 2025-07-02 05:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_onboarding', '0005_alter_customuser_username'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('vehicle_type', models.CharField(choices=[('CAR', 'Car'), ('BIKE', 'Bike'), ('BUS', 'Bus'), ('TRUCK', 'Truck'), ('OTHER', 'Other')], max_length=10)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('owner_name', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'vehicles',
                'ordering': ['vehicle_number'],
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pass_id', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('visitor_name', models.CharField(db_index=True, max_length=255)),
                ('mobile_number', models.CharField(db_index=True, max_length=15)),
                ('email_id', models.EmailField(blank=True, max_length=254)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('P', 'Prefer not to say')], max_length=1)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='visitor_photos/')),
                ('pass_type', models.CharField(choices=[('ONE_TIME', 'One Time'), ('RECURRING', 'Recurring'), ('PERMANENT', 'Permanent')], default='ONE_TIME', max_length=20)),
                ('visiting_date', models.DateField(db_index=True)),
                ('visiting_time', models.TimeField()),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('recurring_days', models.PositiveIntegerField(blank=True, null=True)),
                ('allowing_hours', models.PositiveIntegerField(default=8)),
                ('whom_to_meet', models.CharField(blank=True, max_length=255)),
                ('from_address', models.TextField(blank=True)),
                ('purpose_of_visit', models.TextField()),
                ('belongings_tools', models.TextField(blank=True)),
                ('security_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('BLACKLISTED', 'Blacklisted')], default='PENDING', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='visitor_qrcodes/')),
                ('id_document', models.FileField(blank=True, null=True, upload_to='visitor_documents/')),
                ('entry_time', models.DateTimeField(blank=True, null=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('is_inside', models.BooleanField(default=False)),
                ('entry_otp', models.CharField(blank=True, max_length=6, null=True)),
                ('exit_otp', models.CharField(blank=True, max_length=6, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitors_approved', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitors_all', to='add_visitors.category')),
                ('coming_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitors_from_company', to='user_onboarding.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitors_created', to=settings.AUTH_USER_MODEL)),
                ('host_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_visitors', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='add_visitors.vehicle')),
            ],
            options={
                'db_table': 'visitors',
                'ordering': ['-visiting_date', '-visiting_time'],
            },
        ),
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('ENTRY', 'Entry'), ('EXIT', 'Exit'), ('REJECTED_ENTRY', 'Rejected Entry'), ('EMERGENCY_EXIT', 'Emergency Exit')], max_length=20)),
                ('gate', models.CharField(choices=[('MAIN', 'Main Gate'), ('SIDE', 'Side Gate'), ('EMERGENCY', 'Emergency Gate')], default='MAIN', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('device_info', models.JSONField(blank=True, default=dict)),
                ('security_guard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='add_visitors.visitor')),
            ],
            options={
                'db_table': 'visitor_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['visiting_date', 'status'], name='visitors_visitin_a4b008_idx'),
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['mobile_number', 'visiting_date'], name='visitors_mobile__d0df24_idx'),
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['status', 'is_inside'], name='visitors_status_3bd4e5_idx'),
        ),
        migrations.AddIndex(
            model_name='visitorlog',
            index=models.Index(fields=['visitor', 'action'], name='visitor_log_visitor_ba45c3_idx'),
        ),
        migrations.AddIndex(
            model_name='visitorlog',
            index=models.Index(fields=['created_at', 'action'], name='visitor_log_created_ae2ff8_idx'),
        ),
    ]
