# Generated by Django 5.1.5 on 2025-07-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_visitors', '0002_category_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='entry_otp',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='exit_otp',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
