# Generated by Django 5.1.5 on 2025-07-03 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_visitors', '0003_alter_visitor_entry_otp_alter_visitor_exit_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='from_address',
        ),
    ]
