# Generated by Django 5.1.5 on 2025-07-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_visitors', '0004_remove_visitor_from_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='coming_from',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='pass_type',
            field=models.CharField(choices=[('ONE_TIME', 'One Time'), ('RECURRING', 'Recurring')], default='ONE_TIME', max_length=20),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
