# Generated by Django 5.1.5 on 2025-07-21 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_visitors', '0005_alter_visitor_coming_from_alter_visitor_pass_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitorlog',
            name='gate',
        ),
    ]
