# Generated by Django 5.1.5 on 2025-11-27 07:11

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_visitors', '0006_remove_visitorlog_gate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='visitor_qrcodes/'),
        ),
    ]
