# Generated by Django 5.1.5 on 2025-11-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_visitors', '0007_alter_visitor_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
