# Generated by Django 5.1.5 on 2025-11-28 05:28

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_visitors', '0008_alter_category_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_category_name_case_insensitive'),
        ),
    ]
