# Generated by Django 5.1.5 on 2025-12-17 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_visitors', '0009_category_unique_category_name_case_insensitive'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='entry_otp_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitor',
            name='exit_otp_used',
            field=models.BooleanField(default=False),
        ),
    ]
