# Generated by Django 5.1.5 on 2025-07-09 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles_creation', '0002_add_new_permissions'),
        ('user_onboarding', '0005_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='roles_creation.role'),
        ),
    ]
