# Generated by Django 5.1.6 on 2025-08-19 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_onboarding', '0006_customuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
    ]
