# Generated by Django 5.1.5 on 2025-10-28 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_onboarding', '0008_customuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
    ]
